services:

  mtrcstore-db:
    image: postgres:17.2
    container_name: mtrcstore_db
    restart: always
    ports:
      - ${DB_LOCAL_PORT}:${DB_PORT}
    volumes:
      - mtrcstore-db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}

volumes:
  mtrcstore-db-data: