version: '3.9'

services:

  mtrcstore-db:
    image: postgres
    container_name: mtrcstore_db
    restart: always
    volumes:
      - mtrcstore-db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}