basePath: /
definitions:
  github_com_arefev_mtrcstore_internal_server_model.Metric:
    properties:
      delta:
        description: значение метрики в случае передачи counter
        type: integer
      id:
        description: имя метрики
        type: string
      type:
        description: параметр, принимающий значение gauge или counter
        type: string
      value:
        description: значение метрики в случае передачи gauge
        type: number
    type: object
host: localhost:8080
info:
  contact: {}
  description: Metrics storage service
  title: MetricsStore API
  version: "1.0"
paths:
  /:
    get:
      consumes:
      - text/html
      operationId: getMetric
      produces:
      - text/html
      responses:
        "200":
          description: OK
        "500":
          description: Internal Server Error
      summary: Get metrics list
      tags:
      - Info
  /ping:
    get:
      consumes:
      - text/html
      operationId: pingMetric
      produces:
      - text/html
      responses:
        "200":
          description: OK
        "500":
          description: Internal Server Error
      summary: Check storage status
      tags:
      - Info
  /update:
    post:
      consumes:
      - application/json
      operationId: updateJSONMetric
      parameters:
      - description: Metric's data
        in: body
        name: metric
        required: true
        schema:
          $ref: '#/definitions/github_com_arefev_mtrcstore_internal_server_model.Metric'
      produces:
      - application/json
      responses:
        "200":
          description: Metric's data
          schema:
            $ref: '#/definitions/github_com_arefev_mtrcstore_internal_server_model.Metric'
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Update metric with json format
      tags:
      - Update
  /update/{type}/{name}/{value}:
    post:
      consumes:
      - text/html
      operationId: updateMetric
      parameters:
      - description: metric type [counter, gauge]
        in: path
        name: type
        required: true
        type: string
      - description: metric name
        in: path
        name: name
        required: true
        type: string
      - description: metric value
        in: path
        name: value
        required: true
        type: number
      produces:
      - text/html
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Update metric by type and name
      tags:
      - Update
  /updates/:
    post:
      consumes:
      - application/json
      operationId: updatesMetric
      parameters:
      - description: Metric's data
        in: body
        name: metric
        required: true
        schema:
          items:
            $ref: '#/definitions/github_com_arefev_mtrcstore_internal_server_model.Metric'
          type: array
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Mass update metrics with json format
      tags:
      - Update
  /value/:
    post:
      consumes:
      - application/json
      operationId: findJSONMetric
      parameters:
      - description: Metric's data
        in: body
        name: metric
        required: true
        schema:
          $ref: '#/definitions/github_com_arefev_mtrcstore_internal_server_model.Metric'
      produces:
      - application/json
      responses:
        "200":
          description: Metric's data
          schema:
            $ref: '#/definitions/github_com_arefev_mtrcstore_internal_server_model.Metric'
        "400":
          description: Bad Request
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: Get metric info with json format
      tags:
      - Info
  /value/{type}/{name}:
    get:
      consumes:
      - text/html
      operationId: findMetric
      parameters:
      - description: metric type [counter, gauge]
        in: path
        name: type
        required: true
        type: string
      - description: metric name
        in: path
        name: name
        required: true
        type: string
      produces:
      - text/html
      responses:
        "200":
          description: metric's value, for example 200.4
          schema:
            type: string
        "400":
          description: Bad Request
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: Find metric by type and name
      tags:
      - Info
swagger: "2.0"
tags:
- description: '"Group of requests to get metrics"'
  name: Info
- description: '"Group of requests to update metrics"'
  name: Update
